### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "d3942fadc8644cf8883ca8374ca8c659",
  "accountNumber": "1000000002",
  "amount": 100
}
### quert tranaction
GET http://localhost:8080/transaction/c7785b0578da4afba0af211a47b10d13